minio:
  config:
    aws-minio-credential-provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    aws-minio-packages: org.apache.hadoop:hadoop-aws:3.4.2,software.amazon.awssdk:bundle:2.29.52,software.amazon.awssdk:url-connection-client:2.29.52
    datetime_sub_folder_template: year={yyyy}/month={mm}/day={dd}/run={hhmm}/

    bucket:
      bronze:
        name: raw

      silver:
        name: cleansed

      gold:
        name: aggregated

    environment-specific:
      local:
        host: localhost:9000
        username: minioadmin
        password: minioadmin1!
        accessible: True
        ssl-enabled: False

      dev:
        host: minio:9000
        username: minioadmin
        password: minioadmin1!
        accessible: True
        ssl-enabled: True

      qa:
        host: minio:9000
        username: minioadmin
        password: minioadmin1!
        accessible: True
        ssl-enabled: True

      uat:
        host: minio:9000
        username: minioadmin
        password: minioadmin1!
        accessible: True
        ssl-enabled: True

      prod:
        host: minio:9000
        username: minioadmin
        password: minioadmin1!
        accessible: True
        ssl-enabled: True
